version: '2.4'
services:

  db:
    image: postgres:10.15-alpine
    container_name: kanban-postgres
    volumes:
      - kanban-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cldinf
      - POSTGRES_USER=cldinf
      - POSTGRES_PASSWORD=cldinf

  app:
    container_name: kanban-app
    image: hsrnetwork/kanban-app:1.1
    environment:
      - DB_SERVER=db
      - POSTGRES_DB=cldinf
      - POSTGRES_USER=cldinf
      - POSTGRES_PASSWORD=cldinf
    links:
      - db

  ui:
    container_name: kanban-ui
    image: hsrnetwork/kanban-ui:1.1
    ports:
      - 80:80
    links:
      - app


volumes:
  kanban-data: