version: '2.4'
services:

  db:
    image: postgres:10.15-alpine
    volumes:
      - kanban-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cldinf
      - POSTGRES_USER=cldinf
      - POSTGRES_PASSWORD=cldinf
    networks:
      - storage

  kanban-app:
    image: hsrnetwork/kanban-app:1.1
    environment:
      - DB_SERVER=db
      - POSTGRES_DB=cldinf
      - POSTGRES_USER=cldinf
      - POSTGRES_PASSWORD=cldinf
    networks:
      - backend
      - storage

  kanban-ui:
    image: hsrnetwork/kanban-ui:1.1
    ports:
      - 8080:80
    networks:
      - ui
      - backend

networks:
  ui:
  backend:
    internal: true
  storage:
    internal: true

volumes:
  kanban-data: